In [1]:
import pandas as pd

##### Задание 1  
Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
	- оценка 2 и меньше - низкий рейтинг
	- оценка 4 и меньше - средний рейтинг
	- оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец *class*

In [546]:
ratings_df = pd.read_csv('F:\\Program\\git_base\\GitHub\\MyRepo\\PYDA_07\\ml-latest-small\\ratings.csv', \
                         sep=',', header=0, encoding='UTF-8')
movie_df = pd.read_csv('F:\\Program\\git_base\\GitHub\\MyRepo\\PYDA_07\\ml-latest-small\\movies.csv', \
                         sep=',', header=0, encoding='UTF-8')
joined_df = movie_df.merge(ratings_df, on='movieId', how='left')

In [547]:
joined_df.head()

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7.0,3.0,8.518667e+08
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,9.0,4.0,9.386292e+08
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,13.0,5.0,1.331380e+09
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15.0,2.0,9.979383e+08
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19.0,3.0,8.551901e+08

In [520]:
def class_name(a):
    """определяем класс по рейтингу"""
    if a >= 4.5:
        return "Высокий рейтинг"
    elif a > 2.0:
        return "Средний рейтинг"
    elif a <= 2.0:
        return "Низкий рейтинг"
    else:
        return "Нет данных по рейтингу"

In [548]:
joined_df['class'] = joined_df['rating'].apply(class_name)
joined_df.head()

,movieId,title,genres,userId,rating,timestamp,class
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7.0,3.0,8.518667e+08,Средний рейтинг
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,9.0,4.0,9.386292e+08,Средний рейтинг
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,13.0,5.0,1.331380e+09,Высокий рейтинг
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15.0,2.0,9.979383e+08,Низкий рейтинг
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19.0,3.0,8.551901e+08,Средний рейтинг

##### Задание 4  
Есть мнение, что *"раньше снимали настоящее кино, не то что сейчас"*.  
Ваша задача проверить это утверждение, используя файлы с рейтингами фильмов из материалов занятия.  
Т. е. проверить верно ли, что с ростом года выпуска фильма его средний рейтинг становится ниже.

При этом мы не будем затрагивать субьективные факторы выставления этих рейтингов, а пройдемся по следующему алгоритму:
1. В переменную **years** запишите список из всех годов с **1950 по 2010**.
2. Напишите функцию **production_year**, которая каждой строке из названия фильма выставляет год выпуска.  

Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте следующий алгоритм:
	- для каждой строки пройдите по всем годам списка years
	- если номер года присутствует в названии фильма, то функция возвращает этот год как год выпуска
	- если ни один из номеров года списка years не встретился в названии фильма, то возвращается 1900 год
    
3. Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец **'year'**  
4. Посчитайте средний рейтинг всех фильмов для каждого значения столбца **'year'** и отсортируйте результат по убыванию   рейтинга

In [549]:
joined_df.head()

,movieId,title,genres,userId,rating,timestamp,class
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7.0,3.0,8.518667e+08,Средний рейтинг
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,9.0,4.0,9.386292e+08,Средний рейтинг
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,13.0,5.0,1.331380e+09,Высокий рейтинг
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15.0,2.0,9.979383e+08,Низкий рейтинг
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19.0,3.0,8.551901e+08,Средний рейтинг

In [550]:
joined_df_4 = joined_df

In [551]:
joined_df_4.head()

,movieId,title,genres,userId,rating,timestamp,class
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7.0,3.0,8.518667e+08,Средний рейтинг
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,9.0,4.0,9.386292e+08,Средний рейтинг
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,13.0,5.0,1.331380e+09,Высокий рейтинг
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15.0,2.0,9.979383e+08,Низкий рейтинг
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19.0,3.0,8.551901e+08,Средний рейтинг

In [562]:
years = []
for element in range(1950, 2011):
    years.append(element)

In [ ]:
def production_year (a):
    list_text = a.title.split('(')

In [564]:
def production_year (a):
    list_text = a.title.split('(')
    for word in list_text:
        if word == '1995)':
            return int(word.replace(")", ""))
    return False

joined_df_4['production_year'] = joined_df_4.apply(production_year, axis=1)
joined_df_4['production_yearX2'] = joined_df_4['production_year'] * 2
joined_df_4.head()

ValueError: ("invalid literal for int() with base 10: 'Toy Story '", 'occurred at index 0')

In [558]:
def year_in_years (a):
    companies = years
    if a['production_year'] in companies:
        return a['production_year']
    return 1990

joined_df_4['production_year'] = joined_df_4.apply(year_in_years, axis=1)

#     for year_element in years:
#         for element in joined['production_year']
#         if joined['production_year']
#     if 

joined_df_4

,movieId,title,genres,userId,rating,timestamp,class,production_year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7.0,3.0,8.518667e+08,Средний рейтинг,1995
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,9.0,4.0,9.386292e+08,Средний рейтинг,1995
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,13.0,5.0,1.331380e+09,Высокий рейтинг,1995
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15.0,2.0,9.979383e+08,Низкий рейтинг,1995
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19.0,3.0,8.551901e+08,Средний рейтинг,1995
5,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,20.0,3.5,1.238730e+09,Средний рейтинг,1995
6,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,23.0,3.0,1.148730e+09,Средний рейтинг,1995
7,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,26.0,5.0,1.360088e+09,Высокий рейтинг,1995
8,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,30.0,4.0,9.449431e+08,Средний рейтинг,1995
9,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,37.0,4.0,9.813081e+08,Средний рейтинг,1995
10,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,43.0,4.0,9.747683e+08,Средний рейтинг,1995
11,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,44.0,4.0,8.587071e+08,Средний рейтинг,1995
12,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,47.0,5.0,8.322289e+08,Высокий рейтинг,1995
13,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,48.0,4.0,1.318797e+09,Средний рейтинг,1995
14,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,55.0,3.0,8.559269e+08,Средний рейтинг,1995
15,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,56.0,4.0,1.467005e+09,Средний рейтинг,1995
16,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,63.0,5.0,1.079098e+09,Высокий рейтинг,1995
17,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,67.0,3.0,8.547118e+08,Средний рейтинг,1995
18,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,68.0,4.0,1.194742e+09,Средний рейтинг,1995
19,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,69.0,5.0,1.366831e+09,Высокий рейтинг,1995
20,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,70.0,5.0,8.539542e+08,Высокий рейтинг,1995
21,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,72.0,3.5,1.461779e+09,Средний рейтинг,1995
22,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,73.0,5.0,1.303465e+09,Высокий рейтинг,1995
23,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,75.0,3.0,1.165607e+09,Средний рейтинг,1995
24,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,77.0,4.0,1.163005e+09,Средний рейтинг,1995
25,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,79.0,2.0,1.182995e+09,Низкий рейтинг,1995
26,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,84.0,3.5,1.429911e+09,Средний рейтинг,1995
27,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,86.0,3.0,8.481618e+08,Средний рейтинг,1995
28,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,87.0,3.0,8.586232e+08,Средний рейтинг,1995
29,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,89.0,5.0,1.257620e+09,Высокий рейтинг,1995
...,...,...,...,...,...,...,...,...
100033,159858,The Conjuring 2 (2016),Horror,73.0,3.5,1.473061e+09,Средний рейтинг,1990
100034,159972,Approaching the Unknown (2016),Drama|Sci-Fi|Thriller,15.0,0.5,1.469330e+09,Низкий рейтинг,1990
100035,160080,Ghostbusters (2016),Action|Comedy|Horror|Sci-Fi,15.0,1.0,1.469330e+09,Низкий рейтинг,1990
100036,160271,Central Intelligence (2016),Action|Comedy,15.0,2.5,1.466803e+09,Средний рейтинг,1990
100037,160438,Jason Bourne (2016),Action,62.0,4.0,1.470457e+09,Средний рейтинг,1990
100038,160438,Jason Bourne (2016),Action,287.0,4.5,1.470167e+09,Высокий рейтинг,1990
100039,160440,The Maid's Room (2014),Thriller,624.0,1.5,1.470511e+09,Низкий рейтинг,1990
100040,160563,The Legend of Tarzan (2016),Action|Adventure,15.0,1.0,1.469330e+09,Низкий рейтинг,1990
100041,160563,The Legend of Tarzan (2016),Action|Adventure,287.0,4.0,1.469161e+09,Средний рейтинг,1990
100042,160565,The Purge: Election Year (2016),Action|Horror|Sci-Fi,15.0,2.0,1.469330e+09,Низкий рейтинг,1990
100043,160567,Mike & Dave Need Wedding Dates (2016),Comedy,15.0,4.0,1.469330e+09,Средний рейтинг,1990
100044,160590,Survive and Advance (2013),(no genres listed),56.0,5.0,1.467096e+09,Высокий рейтинг,1990
100045,160656,Tallulah (2016),Drama,547.0,3.5,1.471168e+09,Средний рейтинг,1990
100046,160718,Piper (2016),Animation,547.0,4.0,1.469713e+09,Средний рейтинг,1990
100047,160954,Nerve (2016),Drama|Thriller,NaN,NaN,NaN,Нет данных по рейтингу,1990
100048,161084,My Friend Rockefeller (2015),Documentary,547.0,2.5,1.468248e+09,Средний рейтинг,1990
100049,161155,Sunspring (2016),Sci-Fi,15.0,0.5,1.469330e+09,Низкий рейтинг,1990
100050,161336,Author: The JT LeRoy Story (2016),Documentary,NaN,NaN,NaN,Нет данных по рейтингу,1990
100051,161582,Hell or High Water (2016),Crime|Drama,NaN,NaN,NaN,Нет данных по рейтингу,1990
100052,161594,Kingsglaive: Final Fantasy XV (2016),Action|Adventure|Animation|Drama|Fantasy|Sci-Fi,73.0,3.0,1.474255e+09,Средний рейтинг,1990
100053,161830,Body (2015),Drama|Horror|Thriller,624.0,1.0,1.472493e+09,Низкий рейтинг,1990
100054,161918,Sharknado 4: The 4th Awakens (2016),Action|Adventure|Horror|Sci-Fi,624.0,1.5,1.472930e+09,Низкий рейтинг,1990
100055,161944,The Last Brickmaker in America (2001),Drama,287.0,5.0,1.470168e+09,Высокий рейтинг,1990
100056,162376,Stranger Things,Drama,73.0,4.5,1.474256e+09,Высокий рейтинг,1990
100057,162542,Rustom (2016),Romance|Thriller,611.0,5.0,1.471521e+09,Высокий рейтинг,1990
100058,162672,Mohenjo Daro (2016),Adventure|Drama|Romance,611.0,3.0,1.471524e+09,Средний рейтинг,1990
100059,163056,Shin Godzilla (2016),Action|Adventure|Fantasy|Sci-Fi,NaN,NaN,NaN,Нет данных по рейтингу,1990
100060,163949,The Beatles: Eight Days a Week - The Touring Y...,Documentary,547.0,5.0,1.476419e+09,Высокий рейтинг,1990
100061,164977,The Gay Desperado (1936),Comedy,NaN,NaN,NaN,Нет данных по рейтингу,1990
100062,164979,"Women of '69, Unboxed",Documentary,NaN,NaN,NaN,Нет данных по рейтингу,1990

In [145]:
# joined['title2'] = joined.apply(production_year, axis=1)
# joined{.head()}
joined[joined.index == 99912]

,movieId,title,genres,userId,rating,timestamp,class
99912,143410,Hyena Road,(no genres listed),624.0,2.0,1.474225e+09,Низкий рейтинг

In [191]:
joined_99912 = joined[joined.index == 99911]

In [192]:
joined_99912['title']

99911    Bridge of Spies (2015)
Name: title, dtype: object

In [203]:
s2 = []
s.append(joined_99912['title'].str.split('('))
for element in s:
    s2.append(element) 
s2

[99911    [Bridge of Spies , 2015)]
 Name: title, dtype: object, 99911    [Bridge of Spies , 2015)]
 Name: title, dtype: object]

In [155]:
f = lambda x:"(".join(x for x in x.split() if x not in freq)
joined['title'] = joined['title'].apply(f)

NameError: name 'freq' is not defined